In [80]:
#1. Run the following

import numpy as np
a = np.array([1, 2, 3])
print((a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
rank=np.linalg.matrix_rank(a)
print(rank)
#shape= 1,3
# a[0]=5,a[1]=2,a[2]=3
#rank=1


[1 2 3]
(3,)
1 2 3
[5 2 3]
1


In [81]:
#2. Run the following:

b = np.array([[1, 2, 3],
               [4, 5, 6]])
print(b)
print(b.shape)# shape= 2,3
print(b[0, 0], b[0, 1], b[1, 0])# b[0,0]=1,b[0,1]=2,b[1,0]=4
rank=np.linalg.matrix_rank(b)# rank=2
print(rank)


[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
2


In [84]:
a=np.zeros((2,2))
print(a)
b=np.ones((1,2))
print(b)
c=np.full((2,2), 7)
print(c)
d=np.random.random((2,2))
print(d)
e=np.eye(2)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[0.55303705 0.92341603]
 [0.04000271 0.01075682]]
[[1. 0.]
 [0. 1.]]


In [87]:
#4. Run the following


a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b=a[:2, 1:3]
print(a.shape)# shape= 3,4
print(b.shape)# shape= 2,2
print(b)# [[2 3]
         #[6 7]]

(3, 4)
(2, 2)
[[2 3]
 [6 7]]


In [89]:
#A slice of an array is a view into the same data. Follow the comments in the following snippet

a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b=a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

#last line print? 77 because b is a view of a, so changing b changes a.

2
77


In [ ]:
#6.

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 =a[1:2,:]
print("Row Values Of r1:",row_r1,"\n Row shape of r1:",row_r1.shape)
print("Row Values Of r2:",row_r2,"\n Row shape of r2:",row_r2.shape)
col_r1=a[:,1]#Column values= [2,6,10]
col_r2=a[:,1:2]#Column values= [[2],[6],[10]]
print("col Values Of r1:",col_r1,"\n Colshape of r1:",col_r1.shape)# shape= (3,)
print("Col Values Of r2:",col_r2,"\n Col shape of r2:",col_r2.shape)# shape= (3,1)

Row Values Of r1: [5 6 7 8] 
 Row shape of r1: (4,)
Row Values Of r2: [[5 6 7 8]] 
 Row shape of r2: (1, 4)
col Values Of r1: [ 2  6 10] 
 Colshape of r1: (3,)
Col Values Of r2: [[ 2]
 [ 6]
 [10]] 
 Col shape of r2: (3, 1)


In [94]:
#7. Run the following

a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

#printed arrays are same

[1 4 5]
[1 4 5]


In [100]:
#8..

a = np.array([[1,2], [3, 4], [5, 6]])
b=a[[0,0],[1,1]]
print(b)
c=np.array([a[0,1],a[0,1]])
print(c)

#duplicated



[2 2]
[2 2]


In [107]:
#9

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("values of a",a)
b = np.array([0, 2, 0, 1])
print("values of b",b)

print("selecting index :",a[np.arange(4), b])   # select one element from each row

a[np.arange(4), b] += 10    # add 10 to those elements
print("final:",a)

#we observe that values at positions (0,0),(1,2),(2,0),(3,1) are increased by 10

values of a [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
values of b [0 2 0 1]
selecting index : [ 1  6  7 11]
final: [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
#10.

a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print("first",bool_idx)        # boolean mask
print(a[bool_idx])     # values greater than 2
print(a[a > 2])        # same as above

#same values printed

first [[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [110]:
#11.

x = np.array([1, 2])          # numpy chooses int
print(x.dtype)

y = np.array([1.0, 2.0])      # numpy chooses float
print(y.dtype)

z = np.array([1, 2], dtype=np.int32)   # force int32
print(z.dtype)

int64
float64
int32


In [112]:
#12.

import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))
#answer is [[ 6.  8.]
#           [10. 12.]]

# Elementwise difference
print(x - y)
print(np.subtract(x, y))
#answer is [[-4. -4.]
#           [-4. -4.]]

# Elementwise product
print(x * y)
print(np.multiply(x, y))
#answer is [[ 5. 12.]
#           [21. 32.]]

# Elementwise division
print(x / y)
print(np.divide(x, y))
#answer is [[0.2        0.33333333]
#           [0.42857143 0.5       ]]

# Elementwise square root
print(np.sqrt(x))
#answer is [[1.         1.41421356]
#           [1.73205081 2.        ]]

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [114]:
#13.

v = np.array([9, 10])
w = np.array([11, 12])

print(v.dot(w))        # dot product
print(np.dot(v, w))    # same
#process is different

219
219


In [116]:
#14.

x = np.array([[1, 2], [3, 4]])
v = np.array([9, 10])

print(x.dot(v))        # matrix × vector
print(np.dot(x, v))    # same

#process is different with and without np

[29 67]
[29 67]


In [122]:
#15.

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6, 7], [7, 8, 9]])

print(np.sum(x))
#answer is 10
print(np.sum(x, axis=0))
#answer is [4 6]
print(np.sum(x, axis=1))
#answer is [3 7]

10
[4 6]
[3 7]


In [120]:
#16.

x = np.array([[1,2,3], [3,4,5]])
print(x)
print(x.T)
#rows become columns and vice versa in transpose


[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [130]:
#17.

x=np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
v=np.array([1,0,1])
y=np.zeros(x.shape)
print("shape:",x.shape[0])
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j]=x[i,j]+v[j]
print(y)
#in every iteration of i, all values of j are updated to add v[j] to x[i,j]

shape: 4
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [132]:
#18.

x = np.array([[1, 2, 3], [4, 5, 6], 
              [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Repeat v across all rows of x
v_tiled = np.tile(v, (x.shape[0], 1))

y = x + v_tiled
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [145]:
#19.

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

v = np.array([1, 0, 1])

# Broadcasting automatically expands v across all rows of x
y = x + v
print("y is : ",y)

w=np.array([4,5])
v=np.array([1,2,3])

outer_product = v[:, np.newaxis] * w
print("Outer product:\n", outer_product)

y is :  [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Outer product:
 [[ 4  5]
 [ 8 10]
 [12 15]]


In [148]:
#20

x = np.array([[1,2,3], [4,5,6]])
print("x is:",x)
v=np.array([1,2,3])
print("v is:",v)
y = x + v  # Add v to each row of x using broadcasting
print("y is : ",y)

x is: [[1 2 3]
 [4 5 6]]
v is: [1 2 3]
y is :  [[2 4 6]
 [5 7 9]]


In [151]:
#21.
w=np.array([4,5]).reshape(2,1)
y= x + w  # Add w to each row of x using broadcasting
print("y is :",y)

y is : [[ 5  6  7]
 [ 9 10 11]]


In [152]:
#22
x = np.array([[1,2,3], [4,5,6]])
x=x*2
print("x is:",x)

x is: [[ 2  4  6]
 [ 8 10 12]]
